spring:
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_INITDB_DATABASE:persons}'
      #uri: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:27017/${MONGO_INITDB_DATABASE}/${MONGO_INITDB_DATABASE}'
      port: 27017
      username: '${MONGO_INITDB_ROOT_USERNAME}'
      password: '${MONGO_INITDB_ROOT_PASSWORD}'
  cloud:
    kubernetes:
      discovery:
        register: true
      secrets:
        name: mongodb-secret

      config:
        enabled: true
        sources:
          - namespace: default
            name: mongodb-configmap
      reload:
        enabled: true
        mode: polling
        period: 1000
