apiVersion: v1
kind: Service
metadata:
  name: devops-back-service
spec:
  selector:
    app: devops-back
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 9090 #the port that the service is running on in the cluster
    targetPort: 9090 #the port exposed by the service
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-back
  template:
    metadata:
      labels:
        app: devops-back
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: devops-back
        image: eyaea/devops-back
        imagePullPolicy: "IfNotPresent"


        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 9090 #the port that the container is running on in the cluster
        env:
        - name: MONGO_HOST
          valueFrom:
             configMapKeyRef:
               name: mongodb-configmap 
               key: host  
        - name: MONGO_DB
          valueFrom:
              configMapKeyRef:
                name: mongodb-configmap 
                key: database                  

        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password












