pipeline {
    agent any
    tools {
        maven 'maven-3.9.4' 
    }
     environment {
        DOCKER_IMAGE = "eyaea/devops-demo"
        DOCKER_TAG = "latest"
        DOCKER_REGISTRY = "your-docker-registry-url"
        DOCKER_CREDENTIALS_ID = 'dockerhub'
        SONARQUBE_CREDENTIALS_ID = 'sonartoken'
    }
    stages {
        stage('Chechout scm') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/robinmetro1/jenkins-pipeline.git']])                
            }
        }
        stage('SonarQube analysis for spring app') {
            steps{
               dir('/var/jenkins_home/workspace/devops-test/back') {
                  withSonarQubeEnv(credentialsId: SONARQUBE_CREDENTIALS_ID, installationName: 'sonarserver')
                   { // You can override the credential to be used
                 sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.1.3006:sonar'

                   }
           }
        }
        }

        stage('Build Maven') {
            steps {
                 dir('/var/jenkins_home/workspace/devops-test/back') {
                        sh 'mvn clean package'

                 }
            }
            post {
                success {
                    echo "Success: Maven build completed"
                }
                failure {
                    echo "Failed: Maven build"
                }
            }
        }
    
        stage('Build Docker Image') {
            steps {
                script {
                     dir('/var/jenkins_home/workspace/devops-test/back') {
                    // Build your Docker image
                    def dockerImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", ".")
                    }
                }
            }
        }
       
        stage('Push Docker image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', DOCKER_CREDENTIALS_ID) {
                       def dockerImage = docker.image(env.DOCKER_IMAGE)
                        dockerImage.push(env.DOCKER_TAG)
                    }
                }
            }
            post {
                always{
                    script {
                        sh 'docker logout'
                    }                
                }
            }
        }
        
        stage('Deploy to k8s') {
            steps {
                echo "Deploying..."
                script{
                echo "Running k8s........................"

                }
            }
        }
        
        stage('Test') {
            steps {
                echo "Running tests........................"
                // Add test steps here
            }
        }
    }
}
    


